version: '3'

services:
    web:
        build: .
        container_name: profile-web
        command: ["tail", "-f", "/dev/null"]
        volumes:
            - ./profile:/profile
            - /profile/node_modules
        ports:
            - "3002:3000"