export { default as Loader } from './Loader';
export { default as Navbar } from './Navbar';
export { default as Footer } from './Footer';
export { default as Skills } from './Skills';
export { default as Transactions } from './Transactions';
export { default as Home } from './Home';
export { default as Smartcontracts} from './Smartcontracts';
export { default as Table } from './Table';
export { default as Card } from './Card';
export { default as Input } from './Inputs';
export { default as MyTest } from './MyTest';
export { default as Test } from './Test';
export { default as Campaigns } from './Campaigns';
export { default as CampaignsView } from './CampaignsView';
export { default as CampaignsCreate } from './CampaignsCreate';