export { default as Loader } from './Loader';
export { default as Navbar } from './Navbar';
export { default as Footer } from './Footer';
export { default as Skills } from './Skills';
export { default as Transactions } from './Transactions';
export { default as Home } from './Home';
export { default as Smartcontracts} from './Smartcontracts';
export { default as Table } from './Table';
export { default as MyTest } from './MyTest';
export { default as Test } from './Test';